---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 1h
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.4
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfd
        namespace: kube-system
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    prometheus:
      enable: false
    master:
      resources:
        requests:
          cpu: 21m
          memory: 51Mi
        limits:
          memory: 51Mi
    worker:
      config:
        core:
          sources:
            - pci
            - system
            - usb
      resources:
        requests:
          cpu: 5m
          memory: 48Mi
        limits:
          memory: 48Mi
