---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fairwinds-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.fairwinds.com/stable
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.fairwinds.com/stable
      chart: goldilocks
      version: 8.0.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  values:
    vpa:
      enabled: true
