---
# yaml-language-server: $schema=https://frigate.devbu.io/api/config/schema.json
logger:
  default: info
  # logs:
  #   frigate.record: debug

mqtt:
  host: emqx.home.svc
  port: 1883
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128", "-hwaccel_output_format", "yuv420p"]
  output_args:
    record: preset-record-ubiquiti

objects:
  track: ["person"]
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

# Specify camera's
cameras:
  living_room:
    ffmpeg:
      inputs:
        - path: "rtsp://wyze-bridge.home.svc.cluster.local:8554/living-room-ceiling"
          roles:
            - rtmp
    rtmp:
      enabled: True
