---
# yaml-language-server: $schema=https://frigate.donoso.family/api/config/schema.json
logger:
  default: info
  # logs:
  #   frigate.record: debug

mqtt:
  host: emqx.home.svc
  port: 1883
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  # global_args: ["-hide_banner", "-loglevel", "warning"]
  # input_args: preset-rtsp-generic
  hwaccel_args: preset-vaapi
  # output_args:
  #   record: preset-record-generic

birdseye:
  enabled: false

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 2

record:
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 2
      mode: active_objects

objects:
  track: ["person", "cat", "dog", "car"]
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

go2rtc:
  webrtc:
      candidates:
        - 10.2.1.103:8555
        - stun:8555
  streams:
    backyard:
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@10.0.2.238:554/h264Preview_01_main
    backyard_sub:
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@10.0.2.238:554/h264Preview_01_sub
    entrance:
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@10.0.2.222:554/h264Preview_01_main
    entrance_sub:
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PASSWORD}@10.0.2.222:554/h264Preview_01_sub
    living_room:
      - rtsp://wyze-bridge.home.svc.cluster.local:8554/living-room-ceiling
    living_room_sub:
      - rtsp://wyze-bridge.home.svc.cluster.local:8554/living-room-ceiling-sub
    family_room:
      - rtsp://wyze-bridge.home.svc.cluster.local:8554/family-room
    family_room_sub:
      - rtsp://wyze-bridge.home.svc.cluster.local:8554/family-room-sub

# Specify camera's
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/backyard
          roles: ["record"]
        - path: rtsp://localhost:8554/backyard_sub
          roles: ["detect"]
    detect:
      width: 640
      height: 360
      fps: 10

  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/entrance
          roles: ["record"]
        - path: rtsp://localhost:8554/entrance_sub
          roles: ["detect"]
    detect:
      width: 640
      height: 360
      fps: 10
    zones:
      parking_lot:
        coordinates: 134,360,474,360,516,149,219,107,0,240
    motion:
      mask:
        - 0,360,144,360,139,316,0,297
        - 503,311,538,221,567,125,583,0,483,0,441,0
        - 464,0,440,35,253,43,123,91,0,129,0,0
        - 640,0,640,29,444,28,443,0

  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/living_room_sub
          input_args: preset-rtsp-restream
          roles: ["detect"]
        - path: rtsp://localhost:8554/living_room
          input_args: preset-rtsp-restream
          roles: ["record"]
    detect:
      width: 640
      height: 360
      fps: 10

  family_room:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/family_room_sub
          input_args: preset-rtsp-restream
          roles: ["detect"]
        - path: rtsp://localhost:8554/family_room
          input_args: preset-rtsp-restream
          roles: ["record"]
    detect:
      width: 640
      height: 360
      fps: 10
