---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
  - ./intel-device-plugin-operator/ks.yaml
  - ./e1000e-fix/ks.yaml
  - ./multus/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./metrics-server/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
