---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./intel-device-plugins/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
