---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    template:
      data:
        FRIGATE_RTSP_USER: "{{ .RTSP_USERNAME }}"
        FRIGATE_RTSP_PASSWORD: "{{ .RTSP_PASSWORD }}"
  dataFrom:
    - extract:
        key: reolink
