---
# Area
- { name: "area/bootstrap",          color: "0e8a16" }
- { name: "area/github",             color: "0e8a16" }
- { name: "area/kubernetes",         color: "0e8a16" }
- { name: "area/taskfile",           color: "0e8a16" }
# Distro
- { name: "distro/talos",            color: "ffc300" }
# Renovate
- { name: "renovate/container",      color: "027fa0" }
- { name: "renovate/github-action",  color: "027fa0" }
- { name: "renovate/github-release", color: "027fa0" }
- { name: "renovate/helm",           color: "027fa0" }
# Semantic Type
- { name: "type/patch",              color: "ffec19" }
- { name: "type/minor",              color: "ff9800" }
- { name: "type/major",              color: "f6412d" }
- { name: "type/break",              color: "f6412d" }
# Uncategorized
- { name: "hold/upstream",           color: "ee0701" }
