---
# Areas
area/ansible:
  - changed-files:
      - any-glob-to-any-file: "ansible/**/*"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"
area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/**/*"
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - ".taskfiles/**/*"
          - "Taskfile.yaml"
area/terraform:
  - changed-files:
      - any-glob-to-any-file: "terraform/**/*"
# Clusters
cluster/main:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/**/*"
