[makejinja]
inputs = ["./bootstrap/overrides","./bootstrap/templates"]
output = "./"
exclude_patterns = [".mjfilter.py", "*.partial.yaml.j2"]
data = ["./config.yaml"]
import_paths = ["./bootstrap/scripts"]
loaders = ["plugin:Plugin"]
jinja_suffix = ".j2"
force = true
undefined = "chainable"

[makejinja.delimiter]
block_start = "#%"
block_end = "%#"
comment_start = "#|"
comment_end = "#|"
variable_start = "#{"
variable_end = "}#"
