---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        SECRET_ZONE_HOME_LONGITUDE: "{{ .secret_zone_home_longitude }}"
        SECRET_ZONE_HOME_LATITUDE: "{{ .secret_zone_home_latitude }}"
        SECRET_ZONE_HOME_ELEVATION: "{{ .secret_zone_home_elevation }}"
        SECRET_EXTERNAL_URL: "{{ .secret_external_url }}"
        SECRET_INTERNAL_URL: "{{ .secret_internal_url }}"
  dataFrom:
    - extract:
        key: home-assistant
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-deploykey
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: home-assistant-deploykey
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: home-assistant
        property: github_deploy_key
