---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./externalsecret.yaml
  - ./dnsendpoint.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - ./config/config.yaml
configurations:
  - ./patches/kustomizeconfig.yaml
