---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-0
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: ceph-block
