---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.4.6
    env:
      TZ: '${TIMEZONE}'
      HASS_IP: 10.2.1.100
    envFrom:
      - secretRef:
          name: home-assistant-secrets
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.2.1.100
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          external-dns.alpha.kubernetes.io/target: home.${SECRET_PUBLIC_DOMAIN}
          monitor.stakater.com/enabled: "true"
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &host 'hass.${SECRET_PUBLIC_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.12.0
        env:
          TZ: '${TIMEZONE}'
          EMAIL: jidonoso@gmail.com
          GIT_AUTHOR_NAME: Juan Ignacio Donoso
        workingDir: '/config'
        args:
          - --auth
          - 'none'
          - --user-data-dir
          - '/config/.vscode'
          - --extensions-dir
          - '/config/.vscode'
        ingress:
          enabled: true
          ingressClassName: 'nginx'
          annotations:
            external-dns.alpha.kubernetes.io/target: home.${SECRET_PUBLIC_DOMAIN}
            nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_PUBLIC_DOMAIN}/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_PUBLIC_DOMAIN}/oauth2/start
            hajimari.io/appName: 'Hass Config'
            hajimari.io/icon: cib:visual-studio-code
          hosts:
            - host: &hostvs 'hass-vscode.${SECRET_PUBLIC_DOMAIN}'
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *hostvs
        volumeMounts:
          - name: config
            mountPath: /config
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    resources:
      requests:
        cpu: 48m
        memory: 443M
      limits:
        memory: 709M
