---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wyze-bridge
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    image:
      repository: mrlt8/wyze-bridge
      tag: 2.0.1

    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: wyze-secrets

    service:
      main:
        ports:
          http:
            enabled: true
            port: 5000
          rtmp:
            enabled: true
            port: 1935
          rstp:
            enabled: true
            port: 8554
          hls:
            enabled: true
            port: 8888

    resources:
      requests:
        cpu: 35m
        memory: 500M
      limits:
        memory: 2000M
