---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.donoso.family
      recordType: CNAME
      targets: ["397243cd-c7b6-40cd-8f03-7be2c029033d.cfargotunnel.com"]
