---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflared-secret
    template:
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .CLOUDFLARE_ACCOUNT_TAG }}",
            "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_SECRET }}",
            "TunnelID": "{{ .CLOUDFLARE_TUNNEL_ID }}"
          }
        TunnelID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
  dataFrom:
    - extract:
        key: cloudflare
