---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-restic
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/esphome'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: esphome
  namespace: home
spec:
  sourcePVC: config-esphome-0
  trigger:
    schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: esphome-restic-secret
    cacheCapacity: 5Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
