---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-couchdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: obsidian-couchdb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        COUCHDB_USER: "{{ .OBSIDIAN_COUCHDB_USER }}"
        COUCHDB_PASSWORD: "{{ .OBSIDIAN_COUCHDB_PASSWORD }}"
  dataFrom:
    - extract:
        key: obsidian
