---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data-0
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
