---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./data-pvc-0.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./volsync.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yml=./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
