---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets-source
  namespace: flux-system
spec:
  interval: 30m
  # renovate: datasource=github-releases
  url: https://github.com/external-secrets/external-secrets.git
  ref:
    tag: v0.9.3
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/config/crds/bases/*
    /config/crds/bases/kustomization.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: external-secrets-source
