---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: obsidian-couchdb
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
    - name: onepassword
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/default/obsidian-couchdb/app
  postBuild:
    substitute:
      APP: obsidian-couchdb
      VOLSYNC_CAPACITY: 30Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
