---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: esphome/esphome
      tag: 2023.3.0

    service:
      main:
        ports:
          http:
            port: 6052

    hostNetwork: true

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: home.${SECRET_PUBLIC_DOMAIN}
          monitor.stakater.com/enabled: "true"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_PUBLIC_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_PUBLIC_DOMAIN}/oauth2/start
        hosts:
          - host: &host "esphome.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      esphome-cache:
        enabled: true
        type: emptyDir
        mountPath: /config/.esphome
      config:
        enabled: true
        existingClaim: "esphome-config"

    resources:
      requests:
        cpu: 300m
        memory: 512M
      limits:
        memory: 2048M
