---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: esphome/esphome
      tag: 2023.5.5

    service:
      main:
        ports:
          http:
            port: 6052

    hostNetwork: true

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: home.donoso.family
          monitor.stakater.com/enabled: "true"
          nginx.ingress.kubernetes.io/auth-url: https://auth.donoso.family/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: https://auth.donoso.family/oauth2/start
        hosts:
          - host: &host "esphome.donoso.family"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      esphome-cache:
        enabled: true
        type: emptyDir
        mountPath: /config/.esphome
      config:
        enabled: true
        existingClaim: esphome-config-0

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.13.0
        env:
          TZ: America/Santiago
          EMAIL: jidonoso@gmail.com
          GIT_AUTHOR_NAME: Juan Ignacio Donoso
        workingDir: '/config'
        args:
          - --auth
          - 'none'
          - --user-data-dir
          - '/config/.vscode'
          - --extensions-dir
          - '/config/.vscode'
        ingress:
          enabled: true
          ingressClassName: 'nginx'
          annotations:
            external-dns.alpha.kubernetes.io/target: home.donoso.family
            nginx.ingress.kubernetes.io/auth-url: https://auth.donoso.family/oauth2/auth
            nginx.ingress.kubernetes.io/auth-signin: https://auth.donoso.family/oauth2/start
            hajimari.io/appName: 'EspHome Config'
            hajimari.io/icon: cib:visual-studio-code
          hosts:
            - host: &hostvs 'esphome-vscode.donoso.family'
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *hostvs
        volumeMounts:
          - name: config
            mountPath: /config

    resources:
      requests:
        cpu: 300m
        memory: 512M
      limits:
        memory: 2048M
