---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-webhook
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.donoso.family"
spec:
  ingressClassName: external
  rules:
    - host: flux-webhook.donoso.family
      http:
        paths:
          - path: /hook/
            pathType: Prefix
            backend:
              service:
                name: webhook-receiver
                port:
                  number: 80
