apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Y6L+0/jiHg/MYI9JZoVYySIvL+fgdaxOmIb/OveoDqerL2HNCIdeeg==,iv:IVJLRSp8hrkCQeRE3MGASUe2Yzji+lnU5vLSnnTwTWA=,tag:5Kc5PY37VwIVjE+oX9/o9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vnvhg8504nx02f9sjuxnj4uerku84ye93udvlv0z3dy94e24y93sq5c7z9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMVVHUnBpWXVaYTZRSjl6
            cDVxYlZPMW5yaFBFai83Z1plVGtOOGpJajAwCmZncjdkUWtjazhiQkdhTzVxVTZ2
            dVFJUnhRU0hoeDFrNjZyM2N1QUNFVUEKLS0tIDc5RkxYaEpZUFhxa1FFN1VYK1h4
            ZDhibm5pYm5zTmpPU3lqNk5pK0I3UE0KrKiyd7vQlNJyiHsf/oO1WrC5Xkt2iEC2
            ntdb0a4hSdb5gGG83RBcwHhjg9MaCz8YdQZ6U4v8Gljh/m428p//pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T03:31:51Z"
    mac: ENC[AES256_GCM,data:sZ7402Wg5Cekq939L9aSZlVJDxaJarCNksFrr7sT2iBNTnbF6s2t2ZiSrls/ngJxFkqg3+ruhzPMY4YtEp65zDBWjyfqZU/Jeeb7dUeQ9pSG+ELNBYUFETqkqx0NKxvr3XsvZCssY47NxGSBZTw6T4WJFx+/s7pOpGQIulj0Qws=,iv:oMg+MJJUlgbF5BFTRn7pJqUu8ogHqk2y/2+/vY0JYs8=,tag:2gXLsbkuYdorcmHXvL+8Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
