---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scrypted
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/koush/scrypted
      tag: 18-jammy-full-v0.41.0
    env:
      TZ: America/Santiago
    service:
      main:
        ports:
          http:
            port: &web-port 11080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.donoso.family
        hosts:
          - host: &host "{{ .Release.Name }}.donoso.family"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [44, 109]
    persistence:
      cache:
        enabled: true
        mountPath: /.npm
        type: emptyDir
    volumeClaimTemplates:
      - name: config
        mountPath: /server/volume
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 10m
        memory: 250Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 2000Mi
