---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - emqx
  - esphome
  - frigate
  - home-assistant
  - postgresql
  - scrypted
  - wyze-bridge
  - zigbee2mqtt
  - zwave-js-ui
