---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: booklore-secret
    template:
      data:
        MARIADB_PASSWORD: "{{ .mariadb_password }}"
        MARIADB_ROOT_PASSWORD: "{{ .mariadb_root_password }}"
  dataFrom:
    - extract:
        key: booklore
