---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: go2rtc-secret
    template:
      data:
        DAHUA_PASSWORD: "{{ .NVR_PASSWORD }}"
        DAHUA_SERIAL: "{{ .NVR_SERIAL_NUMBER }}"
        DAHUA_USERNAME: "{{ .NVR_USERNAME }}"
        go2rtc.yaml: |-
          log:
            streams: error # Prevent log spam from UniFi Protect
          api:
            listen: :1984
            origin: "*"
          rtsp:
            listen: :8554
          webrtc:
            listen: :8555
            candidates:
              - 192.168.69.124:8555
              - stun:8555
            ice_servers:
              - urls:
                  - stun:stun.cloudflare.com:3478
          preload:
            dahua.condo_gate_outside: video
            dahua.condo_gate_outside_2: video
            dahua.condo_gate_inside: video
            dahua.condo_gate_inside_2: video
            dahua.condo_street: video
            dahua.condo_street_2: video
            dahua.condo_street_3: video
            dahua.condo_street_4: video
          streams:
            camera.backyard_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.238
            camera.backyard_pool_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.42
            camera.entrance_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.223
            camera.living_room_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.231
            camera.family_room_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.84
            camera.service_yard_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.146
            dahua.condo_gate_outside:
              - "rtsp://{{ .NVR_USERNAME }}:{{ .NVR_PASSWORD }}@127.0.0.1:18554/cam/realmonitor?channel=1&subtype=0#transport=tcp"
            dahua.condo_gate_outside_2:
              - "rtsp://{{ .NVR_USERNAME }}:{{ .NVR_PASSWORD }}@127.0.0.1:18554/cam/realmonitor?channel=11&subtype=0#transport=tcp"
            dahua.condo_gate_inside:
              - "rtsp://{{ .NVR_USERNAME }}:{{ .NVR_PASSWORD }}@127.0.0.1:18554/cam/realmonitor?channel=10&subtype=0#transport=tcp"
            dahua.condo_gate_inside_2:
              - "rtsp://{{ .NVR_USERNAME }}:{{ .NVR_PASSWORD }}@127.0.0.1:18554/cam/realmonitor?channel=2&subtype=0#transport=tcp"
            dahua.condo_street:
              - "rtsp://{{ .NVR_USERNAME }}:{{ .NVR_PASSWORD }}@127.0.0.1:18554/cam/realmonitor?channel=3&subtype=0#transport=tcp"
            dahua.condo_street_2:
              - "rtsp://{{ .NVR_USERNAME }}:{{ .NVR_PASSWORD }}@127.0.0.1:18554/cam/realmonitor?channel=5&subtype=0#transport=tcp"
            dahua.condo_street_3:
              - "rtsp://{{ .NVR_USERNAME }}:{{ .NVR_PASSWORD }}@127.0.0.1:18554/cam/realmonitor?channel=4&subtype=0#transport=tcp"
            dahua.condo_street_4:
              - "rtsp://{{ .NVR_USERNAME }}:{{ .NVR_PASSWORD }}@127.0.0.1:18554/cam/realmonitor?channel=8&subtype=0#transport=tcp"
  dataFrom:
    - extract:
        key: reolink
    - extract:
        key: dahua
