---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-0
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 21Gi
  storageClassName: ceph-block
