---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./emqx
  - ./esphome/ks.yaml
  - ./frigate/ks.yaml
  - ./postgresql/ks.yaml
  - ./scrypted/ks.yaml
  - ./wyze-bridge/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./zwave-js-ui/ks.yaml
