---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-sync
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: obsidian-sync-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # COUCHDB_USER, COUCHDB_PASSWORD
        key: obsidian-sync
