---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: obsidian-sync
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      init-config:
        image: public.ecr.aws/docker/library/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "cp /tmp/config/*.ini /default.d/; ls -lrt /default.d;"]
        volumeMounts:
          - { name: config-file, mountPath: /tmp/config }
          - { name: config-storage, mountPath: /default.d }

    controller:
      type: statefulset

    image:
      repository: public.ecr.aws/docker/library/couchdb
      tag: 3.3.2

    env:
      COUCHDB_USER:
        valueFrom:
          secretKeyRef:
            name: obsidian-sync-secret
            key: couchdb-user
      COUCHDB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: obsidian-sync-secret
            key: couchdb-password

    service:
      main:
        ports:
          http:
            port: 5984

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: home.donoso.family
        hosts:
          - host: &host obsidian-sync.donoso.family
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: obsidian-sync-configmap # overriden by kustomizeconfig
        mountPath: "-"
      config-storage:
        enabled: true
        type: emptyDir
        mountPath: /opt/couchdb/etc/default.d

    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 250Mi

    volumeClaimTemplates:
      - name: data-0
        mountPath: /opt/couchdb/data
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: ceph-block
