---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - external-secret.yaml
  - helm-release.yaml
configMapGenerator:
  - name: obsidian-sync-configmap
    files:
      - config.ini=config/config.ini
configurations:
  - ./patches/kustomizeconfig.yaml
labels:
  - pairs:
      app.kubernetes.io/name: obsidian-sync
      app.kubernetes.io/instance: obsidian-sync
