---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./bazarr
  - ./calibre-web
  - ./kavita
  - ./overseerr
  - ./plex
  - ./prowlarr
  - ./qbittorrent
  - ./radarr
  - ./readarr
  - ./recyclarr
  - ./sonarr
  - ./tautilli
