---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/media/calibre/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  dependsOn:
    - name: external-secrets-stores
    - name: volsync
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
