---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs-system
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./openebs/ks.yaml
