---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.520@sha256:1879baff5b1155fc1dc40cadc0aa509a26d2c5afc3b234473d878e5573579f08

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    env:
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989
      SONARR__APPLICATION_URL: "https://sonarr.donoso.family"
      SONARR__LOG_LEVEL: info
      SONARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: sonarr-secret
            key: api_key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: home.donoso.family
          nginx.ingress.kubernetes.io/auth-url: https://auth.donoso.family/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: https://auth.donoso.family/oauth2/start
        hosts:
          - host: &host "sonarr.donoso.family"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        type: nfs
        server: "${NAS_ADDR}"
        path: /volume1/media
        mountPath: /media

    resources:
      requests:
        cpu: 15m
        memory: 268M
      limits:
        memory: 2357M
