---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wyze-bridge
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wyze-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WYZE_EMAIL: "{{ .WYZE_EMAIL }}"
        WYZE_PASSWORD: "{{ .WYZE_PASSWORD }}"
        API_ID: "{{ .API_ID }}"
        API_KEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: wyze
