---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyze-bridge
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
  values:
    controllers:
      wyze:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mrlt8/wyze-bridge
              tag: 2.10.3-qsv
            env:
              TZ: America/Santiago
              H264_ENC: h264_qsv
              NET_MODE: LAN
              ON_DEMAND: False
              SUBSTREAM: True
              # FFMPEG_LOGLEVEL: debug
              LIBVA_DRIVER_NAME: i965
              WB_AUTH: false
            envFrom:
              - secretRef:
                  name: wyze-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 200m
              limits:
                memory: 1000Mi
                gpu.intel.com/i915: 1
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
    service:
      app:
        controller: wyze
        ports:
          http:
            enabled: true
            port: 5000
          rtmp:
            enabled: true
            port: 1935
          rstp:
            enabled: true
            port: 8554
          hls:
            enabled: true
            port: 8888
          webrtc:
            enabled: true
            port: 8889
    ingress:
      app:
        className: internal
        hosts:
          - host: wyze.blkh.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
