---
# yaml-language-server: $schema=https://kubernetes-schemas.donoso.family/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicaCount: 2
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ingress.donoso.family
        externalIPs: ["10.2.1.110"]
        externalTrafficPolicy: Local
      ingressClassResource:
        default: true
      config:
        client-body-buffer-size: 100M
        client-body-timeout: 120
        client-header-timeout: 120
        enable-brotli: "true"
        enable-real-ip: "true"
        hsts-max-age: 31449600
        keep-alive-requests: 10000
        keep-alive: 120
        proxy-body-size: 0
        proxy-buffer-size: 16k
        ssl-protocols: TLSv1.3 TLSv1.2
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
          namespace: networking
          namespaceSelector:
            any: true
      extraArgs:
        default-ssl-certificate: networking/donoso-family-tls
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/component: controller
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.25.0
      extraEnvs:
        - { name: TEMPLATE_NAME, value: lost-in-space }
        - { name: SHOW_DETAILS, value: "false" }
