---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "donoso-family-production"
spec:
  secretName: "donoso-family-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: donoso.family
  dnsNames:
    - donoso.family
    - "*.donoso.family"
