---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "donoso-family-staging"
spec:
  secretName: "donoso-family-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: donoso.family
  dnsNames:
    - donoso.family
    - "*.donoso.family"
