---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  chartRef:
    kind: OCIRepository
    name: loki
  interval: 1h
  values:
    deploymentMode: SingleBinary
    loki:
      analytics:
        reporting_enabled: false
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: filesystem
        retention_enabled: true
      ingester:
        chunk_encoding: snappy
      limits_config:
        retention_period: 14d
      schemaConfig:
        configs:
          - from: "2024-04-01" # quote
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      server:
        grpc_server_max_recv_msg_size: 10485760 # 10 MiB
        grpc_server_max_send_msg_size: 10485760 # 10 MiB
        log_level: info
      storage:
        type: filesystem
      structuredConfig:
        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://alertmanager-operated.observability.svc.cluster.local:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /rules/fake
    backend:
      replicas: 0
    chunksCache:
      enabled: false
    gateway:
      replicas: 0
    lokiCanary:
      enabled: false
    read:
      replicas: 0
    resultsCache:
      enabled: false
    sidecar:
      image:
        repository: ghcr.io/home-operations/k8s-sidecar
        tag: 2.0.3@sha256:7978b5a757b1cb4f1b0d1c61cf135030b9353a9841457d81c8106eb1cdfe3b4b
      enableUniqueFilenames: true
      rules:
        searchNamespace: ALL
        folder: /rules/fake
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: longhorn
        size: 50Gi
    test:
      enabled: false
    write:
      replicas: 0
