---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: nas
spec:
  allowedNamespaces:
    all: true
  backend:
    filesystem:
      path: /repo
      volume:
        nfs:
          server: black-station.internal
          path: /volume1/VolsyncKopia
  catalog:
    periodicRefresh: true
    refreshInterval: 6h
  create:
    enabled: false
  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  maintenance:
    enabled: true
    schedule:
      quick:
        cron: 0 * * * *
        jitter: 10m
      full:
        cron: 0 2 * * *
        jitter: 30m
  moverDefaults:
    cache:
      contentCacheSizeMb: 512
      metadataCacheSizeMb: 1024
  scheduleDefaults:
    timezone: America/Santiago
