---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-postgresql-data-0
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
