---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass-postgresql
  namespace: home
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 13.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "16.0.0"
    auth:
      username: hass-postgres
      database: hass
      existingSecret: hass-postgresql-secret
    primary:
      persistence:
        enabled: true
        existingClaim: hass-postgresql-data-0
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
