---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: itzg
  namespace: flux-system
spec:
  interval: 2h
  url: https://itzg.github.io/minecraft-server-charts/
