---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./actions-runner-controller.yaml
  # - ./angelnu.yaml
  # - ./aqua.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  # - ./calico.yaml
  # - ./cilium.yaml
  # - ./cloudnative-pg.yaml
  # - ./coredns.yaml
  # - ./crossplane.yaml
  - ./csi-driver-nfs.yaml
  - ./descheduler.yaml
  - ./emqx.yaml
  # - ./enix.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  # - ./fairwinds.yaml
  # - ./falco-security.yaml
  # - ./flagger.yaml
  # - ./gitea.yaml
  - ./grafana.yaml
  # - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  # - ./itzg.yaml
  - ./jetstack.yaml
  # - ./kepler.yaml
  # - ./kubernetes-dashboard.yaml
  # - ./kyverno.yaml
  - ./metallb.yaml
  # - ./metrics-server.yaml
  - ./minio.yaml
  # - ./nextcloud.yaml
  - ./node-feature-discovery.yaml
  - ./oauth2-proxy.yaml
  # - ./piraeus.yaml
  # - ./prometheus-community.yaml
  # - ./redis-operator.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  # - ./stevehipwell.yaml
  # - ./victoria-metrics.yaml
  - ./weaveworks.yaml
  # - ./windmill.yaml
  # - ./xenitab.yaml
