---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oauth2-proxy-values-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        values.yaml: |-
          config:
            clientID: "{{ .client_id }}"
            clientSecret: "{{ .client_secret }}"
            cookieSecret: "{{ .cookie_secret }}"
  dataFrom:
    - extract:
        key: auth0
