---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/descheduler
      chart: descheduler
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-descheduler-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    kind: Deployment
    replicas: 3
    leaderElection:
      enabled: true
    resources:
      requests:
        cpu: 5m
        memory: 48M
      limits:
        memory: 48M
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["descheduler"]
              topologyKey: kubernetes.io/hostname

    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: true
        RemovePodsViolatingNodeTaints:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        RemovePodsViolatingTopologySpreadConstraint:
          enabled: true
          params:
            includeSoftConstraints: true
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
          params:
            nodeFit: true
        LowNodeUtilization:
          enabled: false
        RemoveFailedPods:
          enabled: true
          params:
            failedPods:
              includingInitContainers: true
              excludeOwnerKinds:
                - "Job"
              minPodLifetimeSeconds: 3600
        RemovePodsHavingTooManyRestarts:
          enabled: true
          params:
            podsHavingTooManyRestarts:
              podRestartThreshold: 100
              includingInitContainers: true
