---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./cilium/ks.yaml
  - ./descheduler
  - ./intel-device-plugin
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery
  - ./reloader
  - ./sealed-secrets
  - ./snapshot-controller/ks.yaml
