---
k3s_control_node: true
k3s_server:
  cluster-cidr: 10.42.0.0/16
  disable: ["coredns", "flannel", "local-storage", "metrics-server", "servicelb", "traefik"]
  disable-cloud-controller: true
  disable-helm-controller: false
  disable-kube-proxy: true
  disable-network-policy: true
  docker: false
  etcd-disable-snapshots: true
  etcd-expose-metrics: true
  flannel-backend: "none" # quote
  https-listen-port: 6443
  kube-apiserver-arg: ["anonymous-auth=true"]
  kube-controller-manager-arg: ["bind-address=0.0.0.0"]
  kube-scheduler-arg: ["bind-address=0.0.0.0"]
  node-ip: "{{ ansible_host }}"
  pause-image: registry.k8s.io/pause:3.9
  secrets-encryption: true
  service-cidr: 10.43.0.0/16
  tls-san: ["{{ k3s_registration_address }}"]
  write-kubeconfig-mode: "0644"
