apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: synology
  namespace: monitoring
  labels:
    app: synology
spec:
  selector:
    matchLabels:
      app: synology
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
