---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
    - name: emqx-cluster
    - name: onepassword
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/home/zigbee2mqtt/app
  postBuild:
    substitute:
      APP: zigbee2mqtt
      VOLSYNC_CAPACITY: 1Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home
  wait: false
