# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: &clusterName home-ops

endpoint: https://192.168.86.210:6443

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.9.5
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.32.2

additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - &talosControlplaneVip "192.168.86.210"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-a"
    ipAddress: "192.168.86.21"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/2dcd442954d67662d41c61bdb92165aaf7189aff9997bd011b6968c12ce8d9c0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d8:c4:97:bf:6e:b7"
        dhcp: false
        addresses:
          - "192.168.86.21/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.86.1"
        mtu: 1500
        vip:
          ip: *talosControlplaneVip
  - hostname: "k8s-b"
    ipAddress: "192.168.86.22"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/2dcd442954d67662d41c61bdb92165aaf7189aff9997bd011b6968c12ce8d9c0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d8:c4:97:bf:70:20"
        dhcp: false
        addresses:
          - "192.168.86.22/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.86.1"
        mtu: 1500
        vip:
          ip: *talosControlplaneVip
  - hostname: "k8s-c"
    ipAddress: "192.168.86.23"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/2dcd442954d67662d41c61bdb92165aaf7189aff9997bd011b6968c12ce8d9c0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "1c:69:7a:02:5d:87"
        dhcp: false
        addresses:
          - "192.168.86.23/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.86.1"
        mtu: 1500
        vip:
          ip: *talosControlplaneVip
    patches:
      - "@./patches/k8s-c/longhorn.yaml"

# Controller patches
controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: m

  schematic:
    customization:
      extraKernelArgs:
        - apparmor=0 # Less security, more speed
        - init_on_alloc=0 # Less security, more speed
        - init_on_free=0 # Less security, more speed
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off # Less security, more speed
        - security=none # Less security, more speed
        - net.ifnames=1 # Enable predictable NIC naming
      systemExtensions:
        officialExtensions:
          - siderolabs/gasket-driver
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/mei
          - siderolabs/thunderbolt
          - siderolabs/util-linux-tools

  patches:
    # Configure containerd
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                discard_unpacked_layers = false

    # Disable search domain everywhere
    - |-
      machine:
        network:
          disableSearchDomain: true

    # Enable host dns
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false

    # Mount openebs-hostpath in kubelet
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/mnt/extra
              type: bind
              source: /var/mnt/extra
              options:
                - rbind
                - rshared
                - rw

    # Configure kubelet
    - |-
      machine:
        kubelet:
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
                - 192.168.86.0/24

    # Enable MutatingAdmissionPolicy
    - |-
      cluster:
        apiServer:
          extraArgs:
            runtime-config: admissionregistration.k8s.io/v1alpha1=true
            feature-gates: MutatingAdmissionPolicy=true

    # Configure cluster
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        coreDNS:
            disabled: true
        proxy:
          disabled: true
        scheduler:
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # Configure etcd
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 192.168.86.0/24

    # Configure NFS mount options
    - |
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nconnect=16

    # Configure static host entries
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: 192.168.86.9
              aliases:
                - k8s.black.internal

    # Configure custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_instances: 8192    # Watchdog
          fs.inotify.max_user_watches: 1048576   # Watchdog
          net.core.rmem_max: 67108864            # Cloudflared / QUIC
          net.core.wmem_max: 67108864            # Cloudflared / QUIC

    # Configure udev rules
    - |-
      machine:
        udev:
          rules:
            # Intel GPU
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
            # Coral Edge M.2 TPU
            - SUBSYSTEM=="apex", KERNEL=="apex*", GROUP="44", MODE="0660"

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - actions-runner-system
              - system-upgrade
