---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.1.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      install: true
    grafana:
      enabled: false
      annotations:
        grafana_folder: System
    backgroundController:
      serviceMonitor:
        enabled: false
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - update
                - patch
                - delete
                - get
                - list
    cleanupController:
      serviceMonitor:
        enabled: false
    reportsController:
      serviceMonitor:
        enabled: false
    admissionController:
      replicas: 3
      serviceMonitor:
        enabled: false
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - update
                - delete
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: kyverno
              app.kubernetes.io/component: kyverno
