---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-secret
    template:
      data:
        API_SERVER_KEY: "{{ .api_server_key }}"
        HASS_TOKEN: "{{ .homeassistant_token }}"
        TELEGRAM_BOT_TOKEN: "{{ .telegram_bot_token }}"
        TELEGRAM_ALLOWED_USERS: "{{ .telegram_allowed_users }}"
        TELEGRAM_HOME_CHANNEL: "{{ .telegram_home_channel }}"
  dataFrom:
    - extract:
        key: hermes
