---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources: []
#   - ./namespace.yaml
#   - ./prometheus-operator-crds/ks.yaml
