apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: esphome
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  chart:
    repository: https://k8s-at-home.com/charts/
    name: homer
    version: 2.3.1
  values:
    image:
      repository: b4bz/homer
      tag: v24.05.1
    env:
      TZ: "America/Santiago"
    service:
      port:
        port: 8080
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "1Gi"
    addons:
      codeserver:
        enabled: false
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 2000m
  valueFileSecrets:
  - name: "homer-values"
