---
originRequest:
  originServerName: external.blkh.dev

ingress:
  - hostname: "blkh.dev"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: external.blkh.dev
  - hostname: "*.blkh.dev"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: external.blkh.dev
  - service: http_status:404
