---
originRequest:
  originServerName: external.blkh.dev

ingress:
  - hostname: blkh.dev
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.devbu.io"
    service: *svc
  - service: http_status:404
