---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - soft
    - timeo=30
    - retrans=3
    - noatime
    - nconnect=8
    - rsize=1048576
    - wsize=1048576
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: plex-media-nfs
    volumeAttributes:
      server: black-station.internal
      share: /volume1/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-nfs
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: plex-media-nfs
