---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esphome-secret
    template:
      engineVersion: v2
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .esphome_wifi_ssid }}"
          wifi_password: "{{ .esphome_wifi_password }}"
          wifi_fallback_password: "{{ .esphome_wifi_fallback_password }}"

          api_encryption_key: "{{ .esphome_api_encryption_key }}"
          ota_password: "{{ .esphome_ota_password }}"
          web_password: "{{ .esphome_web_password }}"

  dataFrom:
    - extract:
        key: esphome
      rewrite:
        - regexp:
            source: "(.*)"
            target: "esphome_$1"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-deploykey
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esphome-deploykey
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: esphome
        property: github_deploy_key
