---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: emqx-exporter-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          metrics:
            target: emqx-dashboard.database.svc.cluster.local:18083
            api_key: "{{ .X_EMQX_APIKEY_KEY }}"
            api_secret: "{{ .X_EMQX_APIKEY_SECRET }}"
          probes:
            - target: emqx-listeners.database.svc.cluster.local:1883
  dataFrom:
    - extract:
        key: emqx
