---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-secrets
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_ZONE_HOME_LONGITUDE: "{{ .secret_zone_home_longitude }}"
        SECRET_ZONE_HOME_LATITUDE: "{{ .secret_zone_home_latitude }}"
        SECRET_ZONE_HOME_ELEVATION: "{{ .secret_zone_home_elevation }}"
        SECRET_EXTERNAL_URL: "{{ .secret_external_url }}"
        SECRET_INTERNAL_URL: "{{ .secret_internal_url }}"
        SECRET_RECORDER_DB_URL: "postgresql://{{ .hass_username }}:{{ .hass_password }}@hass-postgresql/hass"
  dataFrom:
    - extract:
        key: hass-postgres
        property: hass_password
    - extract:
        key: hass-postgres
        property: hass_username
    - extract:
        key: home-assistant
