---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  path: ./kubernetes/apps/longhorn-system/longhorn/app
  postBuild:
    substitute:
      APP: longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: longhorn-system
  timeout: 5m
  wait: false # no flux ks dependents
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storageclass
  namespace: longhorn-system
spec:
  dependsOn:
    - name: longhorn
  interval: 1h
  path: ./kubernetes/apps/longhorn-system/longhorn/storageclass
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: longhorn-system
  timeout: 5m
  wait: false # no flux ks dependents
