---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/calibre-web
      tag: version-0.6.18

    env:
      TZ: America/Santiago
      PGID: 65539
      DOCKER_MODS: "linuxserver/calibre-web:calibre"

    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-0
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 10.2.1.50
            path: /volume1/media
        mountPath: /media

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          external-dns.alpha.kubernetes.io/target: home.donoso.family
          nginx.ingress.kubernetes.io/auth-url: https://auth.donoso.family/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: https://auth.donoso.family/oauth2/start
        hosts:
        - host: calibre-web.donoso.family
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - calibre-web.donoso.family

    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 458M
