---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - onepassword-connect-secret.sops.yaml
  - helm-release.yaml
labels:
  - pairs:
      app.kubernetes.io/name: stores
      app.kubernetes.io/instance: onepassword
      app.kubernetes.io/part-of: external-secrets
