---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hass-postgresql-secret
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hass-postgresql-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .hass_password }}"
        postgres-password: "{{ .admin_password }}"
  dataFrom:
    - extract:
        # postgres-password, password
        key: hass-postgres
