---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.6
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: false
    replicaCount: 1
    leaderElect: false
