apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:5VHmsLYRuQhMeZKzMlmunD2dn2/JR/LUpGGA4I16WEQ=,iv:L0fFaVRJPAJqR45iyaEHKDJGTDd+RXa8MFOH+bCNC8o=,tag:nhhyhYcKxYc+uLbkLoi0iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vnvhg8504nx02f9sjuxnj4uerku84ye93udvlv0z3dy94e24y93sq5c7z9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY1VhMFZEMHBIcGdaU3U4
            WUgzZUwrVWltbk5zVXZlaEd4WHVjSnVycDJRCm1ldVpGNk5ZbDFCd2pIVHVvNkl5
            aEt6eC9KSWw5YVRJbE9CaWNaOHdtZ1kKLS0tIDdMN0NHcHR6SGdmUkRvWVhDRWFv
            RGtQWHdGcUxXTVJQVlpDUmExZHg4YkEK2x9F7vd+uKUnZL/RE0DVzui4kCX13cbY
            zqMLKyz9sYRQmdUkqjVVuXLkyZMDSSOUErW8IiwlTvSXW4YuhL9Crw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T03:31:51Z"
    mac: ENC[AES256_GCM,data:gpBR7zh8H1Zj8O5uJ4xSgL3/St5zpVlhI/GkjB1gXMKUWU6pvjeizh4cnJTkz2vHqZYTeOxEcw+cjEjF5VJHSOzAuAhXnJE9BJpCocG84sDUtjDmIduVsuQ0V7O54EC9HKxQdbUgSDtqUpZDqIVcErY4aEthuXkfujkOb0qAOqQ=,iv:Y+MN1h9CP4EBtb6+u4LmyXP59lyeEH/lM9yX8MJ9NEE=,tag:7hvDk9UtF0mjOYHefYa4LQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
