---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hass-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hass-mcp-secret
    template:
      data:
        HOMEASSISTANT_TOKEN: "{{ .hass_token }}"
  dataFrom:
    - extract:
        key: home-assistant
