---
# yaml-language-server: $schema=https://kubernetes-schemas.donoso.family/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: donoso-family
  namespace: networking
spec:
  secretName: donoso-family-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: donoso.family
  dnsNames:
    - donoso.family
    - "*.donoso.family"
