---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-slow
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.2.1.50
  share: /volume1/media
reclaimPolicy: Delete
volumeBindingMode: Immediate
# Note: The first two options are strictly for NFSv4.2
mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
