---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      calibre-web:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542 # gladius:external-services

        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/calibre-web
              tag: 0.6.24@sha256:a46698bcb41c028625882ef36e3e5eab2b5c4520677ad52d3cbb004431fb21da
            env:
              CACHE_DIR: /cache
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 470M
              limits:
                memory: 470M

    service:
      app:
        controller: calibre-web
        ports:
          http:
            port: 8083

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.blkh.dev
        className: internal
        hosts:
          - host: calibre-web.blkh.dev
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: calibre-web
        advancedMounts:
          calibre-web:
            app:
              - path: /config
      media:
        type: nfs
        server: black-station.internal
        path: /volume1/media
        globalMounts:
          - path: /media
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
