apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:Ruhhlakk26tpOQ+r9/KfP8jSHUxvQsvhJFzi4XHgara+QHix0k4FAzNxX96Gdj2i01HCGsIuLNbHC+j3hKMLFdhQOAtO+omvIWc=,iv:fHTubEjaurFkCukTjUr/GrEkx5sudtD7SF53mV7DLc0=,tag:mSXi3DEc8GAFXGKawieeEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vnvhg8504nx02f9sjuxnj4uerku84ye93udvlv0z3dy94e24y93sq5c7z9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeGM5SU5Xblc2N3Y3c3VZ
            bm92dUgyUXJtZ0pSTE1DN0R2TE9VblI4YWxBCjVyNmM1eFZTNFVOaTFCL0Z3ZTQr
            c2YwUU5qZFFUd3lFdm1uYmxGZThzUDQKLS0tICtCRHptZ1Y4d2hiSnVYZHFSeVZ6
            dTR3Z0VwZjRGNGk5bEJmNURsR0hkQzgKAZIrxzBgaPQQFImgUPHEpm5y9cZju2BX
            +LCBhBo5ttpEisuWvVWmFhZlyVci3F8t7SCyOlhor61JbmobyxKa0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T16:00:40Z"
    mac: ENC[AES256_GCM,data:uXNlkKS0HpTEntV/Bh0LttTac6qJesSGHY/t161DMbmkKF9iEl1CuIldnNDlDoCGkd262O211CfIXek0jAmj8yBY88bd88vdpDg4c7NcSjisgku6UYl8mf05zCJkdDwg8jpCWBNj6Q1crn3uJ3VJJVmj0gZ94nAG4OnGQUkjIzc=,iv:+8LEUS6DU5XC9zPs4C15sZmBC709LemjMpSsymGAuZc=,tag:jgjtY3Wdvy5cMH/+RfEKPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
