---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/onedr0p/readarr-develop
      tag: 0.1.4.1596@sha256:afd5b40e56e75f2173ed683f7a20011faf5a4af78b115fcf9cb72bd6bab82545

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    env:
      READARR__INSTANCE_NAME: Readarr
      READARR__PORT: &port 8787
      READARR__APPLICATION_URL: "https://readarr.${SECRET_PUBLIC_DOMAIN}"
      READARR__LOG_LEVEL: info

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "home.${SECRET_PUBLIC_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_PUBLIC_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_PUBLIC_DOMAIN}/oauth2/start
        hosts:
          - host: &host readarr.${SECRET_PUBLIC_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: readarr-config

      media:
        enabled: true
        type: nfs
        server: "${NAS_ADDR}"
        path: /volume1/media
        mountPath: /media

    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 1408M
