---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/external-secrets/charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.14.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-helm-values
