---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: emqx-operator
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: emqx-operator
    replicaCount: 2
    image:
      repository: ghcr.io/emqx/emqx-operator
