---
name: "Kubeconform"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "kubernetes/main/**"

env:
  SCHEMA_DIR: /home/runner/crds

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ["kubernetes/main"]
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@2986852ad836768dfea7781f31828eb3e17990fa # v1.6.2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Tools
        shell: bash
        run: brew install kubeconform kustomize

      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Extract files from container image
        shell: bash
        run: |
          mkdir -p ${{ env.SCHEMA_DIR }}
          docker run --rm \
              -v ${{ env.SCHEMA_DIR }}:/crds \
              -u $(id -u) \
              --entrypoint /bin/sh \
              ghcr.io/onedr0p/kubernetes-schemas:latest \
              -c "cp -r /usr/share/nginx/html/* /crds"

      - name: Run kubeconform
        shell: bash
        run: bash ./.github/scripts/kubeconform.sh ${{ matrix.path }} ${{ env.SCHEMA_DIR }}
