---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      TZ: America/Santiago
    hajimari:
      title: Apps
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: false
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
          - flux-system
          - monitoring
          - networking
          - home
          - media
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.donoso.family
          nginx.ingress.kubernetes.io/auth-url: https://auth.donoso.family/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: https://auth.donoso.family/oauth2/start
          hajimari.io/enable: "false"
        hosts:
          - host: &host apps.donoso.family
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
