---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: obsidian-sync-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # COUCHDB_USER, COUCHDB_PASSWORD
        key: obsidian-sync
