---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: donoso-family
spec:
  secretName: donoso-family-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: donoso.family
  dnsNames: ["donoso.family", "*.donoso.family"]
