---
- name: Cluster kube-vip
  hosts: master
  serial: 1
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Ensure Kubernetes is running
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: started

    - name: Upgrade kube-vip
      ansible.builtin.template:
        src: templates/kube-vip-static-pod.yaml.j2
        dest: "{{ k3s_server_pod_manifests_dir }}/kube-vip-static-pod.yaml"
        mode: preserve
