---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
