---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/repos/app-template
resources:
  - ./repos
  # - ./cloudflare-tunnel/ks.yaml
  # - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  # - ./ingress-nginx/ks.yaml
