---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./repos
  - ./cloudflare-dns/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./echo-server/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./unifi-dns/ks.yaml
